module_label(' read')
module_menu(' png','modules/00%20read/png.js')
module_menu(' stl','modules/00%20read/stl.js')
module_menu(' svg','modules/00%20read/svg.js')
module_menu(' text','modules/00%20read/text.js')
module_label(' input')
module_menu(' video','modules/05%20input/video.js')
module_label(' toolpath')
module_label('  machines')
module_label('   vinyl cutter')
module_menu('   Cricut','modules/10%20toolpath/10%20machines/10%20vinyl%20cutter/Cricut.js')
module_menu('   GCC','modules/10%20toolpath/10%20machines/10%20vinyl%20cutter/GCC.js')
module_menu('   Roland GX-GS-24','modules/10%20toolpath/10%20machines/10%20vinyl%20cutter/Roland%20GX-GS-24.js')
module_menu('   Silhouette Cameo','modules/10%20toolpath/10%20machines/10%20vinyl%20cutter/Silhouette%20Cameo.js')
module_label('   laser cutter')
module_menu('   Epilog','modules/10%20toolpath/10%20machines/20%20laser%20cutter/Epilog.js')
module_menu('   Trotec','modules/10%20toolpath/10%20machines/20%20laser%20cutter/Trotec.js')
module_label('   precision mill')
module_menu('   Othermill-Bantam Tools','modules/10%20toolpath/10%20machines/30%20precision%20mill/Othermill-Bantam%20Tools.js')
module_menu('   Roland MDX-iModela','modules/10%20toolpath/10%20machines/30%20precision%20mill/Roland%20MDX-iModela.js')
module_menu('   Roland SRM-20','modules/10%20toolpath/10%20machines/30%20precision%20mill/Roland%20SRM-20.js')
module_label('   large mill')
module_menu('   ShopBot','modules/10%20toolpath/10%20machines/40%20large%20mill/ShopBot.js')
module_label('  formats')
module_menu('  dxf','modules/10%20toolpath/20%20formats/dxf.js')
module_menu('  g-code','modules/10%20toolpath/20%20formats/g-code.js')
module_menu('  svg','modules/10%20toolpath/20%20formats/svg.js')
module_label('  view')
module_menu('  view toolpath','modules/10%20toolpath/30%20view/view%20toolpath.js')
module_label(' processes')
module_label('  cut')
module_menu('  raster','modules/15%20processes/10%20cut/raster.js')
module_label('  mill raster')
module_menu('  2.5D','modules/15%20processes/20%20mill%20raster/2.5D.js')
module_menu('  2D','modules/15%20processes/20%20mill%20raster/2D.js')
module_menu('  3D','modules/15%20processes/20%20mill%20raster/3D.js')
module_label(' file')
module_menu(' save','modules/20%20file/save.js')
module_label(' websockets')
module_menu(' device','modules/30%20websockets/device.js')
module_menu(' echo','modules/30%20websockets/echo.js')
module_menu(' print','modules/30%20websockets/print.js')
module_menu(' pyserial','modules/30%20websockets/pyserial.js')
module_menu(' serial','modules/30%20websockets/serial.js')
module_menu(' udp','modules/30%20websockets/udp.js')
module_menu(' websocket template','modules/30%20websockets/websocket%20template.js')
module_label(' ui')
module_menu(' bar graph','modules/40%20ui/bar%20graph.js')
module_menu(' button window','modules/40%20ui/button%20window.js')
module_menu(' color','modules/40%20ui/color.js')
module_menu(' label simple','modules/40%20ui/label%20simple.js')
module_menu(' label','modules/40%20ui/label.js')
module_menu(' note','modules/40%20ui/note.js')
module_menu(' slider','modules/40%20ui/slider.js')
module_menu(' text window','modules/40%20ui/text%20window.js')
module_label(' convert')
module_label('  rgba')
module_menu('  jpg','modules/45%20convert/10%20rgba/jpg.js')
module_menu('  png','modules/45%20convert/10%20rgba/png.js')
module_label('  svg')
module_menu('  array','modules/45%20convert/20%20svg/array.js')
module_menu('  image','modules/45%20convert/20%20svg/image.js')
module_label(' image')
module_menu(' boundingbox','modules/50%20image/boundingbox.js')
module_menu(' color separation','modules/50%20image/color%20separation.js')
module_menu(' crop','modules/50%20image/crop.js')
module_menu(' distance transform','modules/50%20image/distance%20transform.js')
module_menu(' dogbone','modules/50%20image/dogbone.js')
module_menu(' edge detect','modules/50%20image/edge%20detect.js')
module_menu(' function','modules/50%20image/function.js')
module_menu(' motion detect','modules/50%20image/motion%20detect.js')
module_menu(' offset','modules/50%20image/offset.js')
module_menu(' orient edges','modules/50%20image/orient%20edges.js')
module_menu(' palette','modules/50%20image/palette.js')
module_menu(' raster mask','modules/50%20image/raster%20mask.js')
module_menu(' size','modules/50%20image/size.js')
module_menu(' threshold','modules/50%20image/threshold.js')
module_menu(' vector mask','modules/50%20image/vector%20mask.js')
module_menu(' vectorize','modules/50%20image/vectorize.js')
module_label(' mesh')
module_menu(' height map','modules/55%20mesh/height%20map.js')
module_menu(' rotate','modules/55%20mesh/rotate.js')
module_menu(' slice raster','modules/55%20mesh/slice%20raster.js')
module_label(' frep')
module_label('  shapes 2D')
module_menu('  arc','modules/60%20frep/10%20shapes%202D/arc.js')
module_menu('  circle','modules/60%20frep/10%20shapes%202D/circle.js')
module_menu('  function','modules/60%20frep/10%20shapes%202D/function.js')
module_menu('  involute gear','modules/60%20frep/10%20shapes%202D/involute%20gear.js')
module_menu('  involute rack','modules/60%20frep/10%20shapes%202D/involute%20rack.js')
module_menu('  polygon','modules/60%20frep/10%20shapes%202D/polygon.js')
module_menu('  rectangle','modules/60%20frep/10%20shapes%202D/rectangle.js')
module_menu('  right triangle','modules/60%20frep/10%20shapes%202D/right%20triangle.js')
module_menu('  triangle','modules/60%20frep/10%20shapes%202D/triangle.js')
module_label('  shapes 3D')
module_menu('  cone','modules/60%20frep/20%20shapes%203D/cone.js')
module_menu('  cube','modules/60%20frep/20%20shapes%203D/cube.js')
module_menu('  cylinder','modules/60%20frep/20%20shapes%203D/cylinder.js')
module_menu('  function','modules/60%20frep/20%20shapes%203D/function.js')
module_menu('  lattice','modules/60%20frep/20%20shapes%203D/lattice.js')
module_menu('  menger','modules/60%20frep/20%20shapes%203D/menger.js')
module_menu('  pyramid','modules/60%20frep/20%20shapes%203D/pyramid.js')
module_menu('  sphere','modules/60%20frep/20%20shapes%203D/sphere.js')
module_menu('  torus','modules/60%20frep/20%20shapes%203D/torus.js')
module_label('  operators')
module_menu('  add','modules/60%20frep/30%20operators/add.js')
module_menu('  blend','modules/60%20frep/30%20operators/blend.js')
module_menu('  clearance','modules/60%20frep/30%20operators/clearance.js')
module_menu('  intersect','modules/60%20frep/30%20operators/intersect.js')
module_menu('  morph','modules/60%20frep/30%20operators/morph.js')
module_menu('  subtract','modules/60%20frep/30%20operators/subtract.js')
module_label('  transforms')
module_menu('  extrude','modules/60%20frep/40%20transforms/extrude.js')
module_menu('  inflate','modules/60%20frep/40%20transforms/inflate.js')
module_menu('  reflect','modules/60%20frep/40%20transforms/reflect.js')
module_menu('  repeat linear','modules/60%20frep/40%20transforms/repeat%20linear.js')
module_menu('  repeat rotary','modules/60%20frep/40%20transforms/repeat%20rotary.js')
module_menu('  revolve','modules/60%20frep/40%20transforms/revolve.js')
module_menu('  rotate','modules/60%20frep/40%20transforms/rotate.js')
module_menu('  scale','modules/60%20frep/40%20transforms/scale.js')
module_menu('  shear','modules/60%20frep/40%20transforms/shear.js')
module_menu('  shell','modules/60%20frep/40%20transforms/shell.js')
module_menu('  slice','modules/60%20frep/40%20transforms/slice.js')
module_menu('  taper','modules/60%20frep/40%20transforms/taper.js')
module_menu('  translate','modules/60%20frep/40%20transforms/translate.js')
module_label('  view')
module_menu('  render (CPU)','modules/60%20frep/50%20view/render%20(CPU).js')
module_menu('  render (GPU)','modules/60%20frep/50%20view/render%20(GPU).js')
module_menu('  slice','modules/60%20frep/50%20view/slice.js')
module_label(' math')
module_menu(' benchmark','modules/65%20math/benchmark.js')
module_menu(' dyadic','modules/65%20math/dyadic.js')
module_menu(' glsl_benchmark','modules/65%20math/glsl_benchmark.js')
module_menu(' parallel','modules/65%20math/parallel.js')
module_menu(' scalar','modules/65%20math/scalar.js')
module_label(' object')
module_menu(' construct','modules/67%20object/construct.js')
module_menu(' download','modules/67%20object/download.js')
module_menu(' set','modules/67%20object/set.js')
module_menu(' string','modules/67%20object/string.js')
module_menu(' view','modules/67%20object/view.js')
module_label(' defaults')
module_menu(' Othermill defaults','modules/70%20defaults/Othermill%20defaults.js')
module_menu(' PCB defaults (mm)','modules/70%20defaults/PCB%20defaults%20(mm).js')
module_menu(' PCB defaults','modules/70%20defaults/PCB%20defaults.js')
module_menu(' Roland Mill defaults','modules/70%20defaults/Roland%20Mill%20defaults.js')
module_label(' iterate')
module_menu(' step and delay','modules/75%20iterate/step%20and%20delay.js')
module_menu(' step','modules/75%20iterate/step.js')
module_label(' event')
module_menu(' delay','modules/78%20event/delay.js')
module_menu(' generate','modules/78%20event/generate.js')
module_menu(' pause','modules/78%20event/pause.js')
module_menu(' sequence','modules/78%20event/sequence.js')
module_label(' network')
module_menu(' apa','modules/80%20network/apa.js')
module_label(' character')
module_menu(' convert','modules/85%20character/convert.js')
module_menu(' in out','modules/85%20character/in%20out.js')
module_menu(' parse','modules/85%20character/parse.js')
module_menu(' variable','modules/85%20character/variable.js')
module_label(' string')
module_menu(' format','modules/88%20string/format.js')
module_menu(' variables','modules/88%20string/variables.js')
module_label(' Solidworks xDesign')
module_label('  svg')
module_menu('  ExtractFaces','modules/90%20Solidworks%20xDesign/10%20svg/ExtractFaces.js')
module_menu('  Honeycomb','modules/90%20Solidworks%20xDesign/10%20svg/Honeycomb.js')
module_menu('  PCB','modules/90%20Solidworks%20xDesign/10%20svg/PCB.js')
module_menu('  SelectFace','modules/90%20Solidworks%20xDesign/10%20svg/SelectFace.js')
module_label('  stl')
module_menu('  stl','modules/90%20Solidworks%20xDesign/20%20stl/stl.js')
module_label(' dev')
module_menu(' log','modules/95%20dev/log.js')
module_label(' library')
module_menu(' globals','modules/97%20library/globals.js')
module_menu(' library','modules/97%20library/library.js')
module_menu(' threejs','modules/97%20library/threejs.js')
module_label(' module')
module_menu(' blank','modules/99%20module/blank.js')
module_menu(' create','modules/99%20module/create.js')
module_menu(' delete','modules/99%20module/delete.js')
module_menu(' move','modules/99%20module/move.js')

